services:
  postgres:
    image: postgres:18
    container_name: github-postgres

    environment:
      POSTGRES_DB: github_etl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  etl:
    build: .
    container_name: github-etl

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PYTHONUNBUFFERED: "1"

    env_file:
      - .env

    command: >
      sh -c "
      alembic upgrade head &&
      python -m src.main
      "

volumes:
  postgres_data:
