"""remove_last_activity_days_repositories

Revision ID: dee60f131bba
Revises: 86b44d70b08d
Create Date: 2026-07-13 12:34:01.487855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee60f131bba'
down_revision: Union[str, Sequence[str], None] = '86b44d70b08d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_activity_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('last_activity_days', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
