"""unique_name_owners

Revision ID: 86b44d70b08d
Revises: b8480912c1e2
Create Date: 2026-07-10 20:29:55.678147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b44d70b08d'
down_revision: Union[str, Sequence[str], None] = 'b8480912c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'owners', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'owners', type_='unique')
    # ### end Alembic commands ###
