"""add_owner_id_etl_state

Revision ID: ae630ec68c5a
Revises: dee60f131bba
Create Date: 2026-07-13 14:53:51.166032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae630ec68c5a'
down_revision: Union[str, Sequence[str], None] = 'dee60f131bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('etl_state', sa.Column('owner_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(
        "etl_state_pkey",
        "etl_state",
        type_="primary",
    )

    op.create_primary_key(
        "etl_state_pkey",
        "etl_state",
        ["entity", "owner_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "etl_state_pkey",
        "etl_state",
        type_="primary",
    )

    op.create_primary_key(
        "etl_state_pkey",
        "etl_state",
        ["entity"],
    )
    
    op.drop_column('etl_state', 'owner_id')
    # ### end Alembic commands ###
