"""unique_name_languages

Revision ID: b8480912c1e2
Revises: e7a4b0c9d1f2
Create Date: 2026-07-10 15:11:25.685113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8480912c1e2'
down_revision: Union[str, Sequence[str], None] = 'e7a4b0c9d1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'languages', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'languages', type_='unique')
    # ### end Alembic commands ###
